<?php

namespace common\modules\subject\models;

use common\models\ClientAndSubject;
use Yii;

/**
 * This is the model class for table "crud".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $title
 * @property string|null $keywords
 * @property string|null $description
 * @property int $status
 *
 * @property ClientAndSubject[] $clientAndSubjects
 */
class Subject extends \yii\db\ActiveRecord
{
    public $tags;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'subjects';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['keywords', 'description'], 'safe'],
            [['status'], 'required'],
            [['status'], 'integer'],
            [['name', 'title'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'title' => 'Title',
            'keywords' => 'Keywords',
            'description' => 'Description',
            'status' => 'Status',
        ];
    }

    /**
     * Gets query for [[ClientAndSubjects]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getClientAndSubjects()
    {
        return $this->hasMany(ClientAndSubject::className(), ['clientId' => 'id']);
    }

    public function beforeSave($insert)
    {
        $this->keywords = implode(", ", $this->keywords);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
