<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add…' => '添加',
    'Close' => '关闭',
    'Description' => '详细描述',
    'Drop Files Here…' => '拖动文件到此处...',
    'Edit' => '修改',
    'Edit information' => '修改描述',
    'Name' => '图片名',
    'Remove' => '删除',
    'Save changes' => '保存',
    'Select all' => '全选',
    'Uploading images…' => '正在上传文件...',
    'Error loading images!' => '',
];
